=== 7Silvan/ncl/XmlDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT tasks (task*)>
<!ELEMENT task (name, description, date)>

<!ATTLIST task
id CDATA #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT date (#PCDATA)>

<!-- 
<!ATTLIST task
userName CDATA #REQUIRED>
-->

=== 7Silvan/ncl/conf/tasks.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tasks SYSTEM "XmlDTD.dtd">
   <tasks>
      <task>
         <name>1</name>
         <description>first</description>
         <contacts>0991234567</contacts>
         <date>2012-01-28 15:11:15</date>
      </task>
      <task>
         <name>2</name>
         <description>second</description>
         <contacts>0661234567</contacts>
         <date>2012-01-28 15:12:15</date>
      </task>
      <task>
         <name>3</name>
         <description>third</description>
         <contacts>0501234567</contacts>
         <date>2012-01-28 15:11:20</date>
      </task>
      <task>
         <name>4</name>
         <description>fourth</description>
         <contacts>0542234567</contacts>
         <date>2012-01-28 15:11:23</date>
      </task>
      <task>
         <name>5</name>
         <description>fifth</description>
         <contacts>0441234567</contacts>
         <date>2012-01-28 15:11:26</date>
      </task>
   </tasks>
